### ISSUE TITLE
Some Unknown Issues

### ISSUE THREAD

**Issue by JustZerooo** [puff/EazyDevirt#18]
```log
[*] Executing ResourceParsing...
[!] Failed to find VM resource stream getter method.
[!] Failed to find VM resource stream initialization method.
[!] Failed to find valid VM resource modulus string method. Have strings been decrypted?
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at EazyDevirt.Devirtualization.Pipeline.ResourceParsing.Init() in D:\GitHub\EazyDevirt\src\EazyDevirt\Devirtualization\Pipeline\ResourceParsing.cs:line 98
   at EazyDevirt.Devirtualization.Pipeline.ResourceParsing.Run() in D:\GitHub\EazyDevirt\src\EazyDevirt\Devirtualization\Pipeline\ResourceParsing.cs:line 106
   at EazyDevirt.Devirtualization.Devirtualizer.Run() in D:\GitHub\EazyDevirt\src\EazyDevirt\Devirtualization\Devirtualizer.cs:line 28
   at EazyDevirt.Program.Run(DevirtualizationOptions options) in D:\GitHub\EazyDevirt\src\EazyDevirt\Program.cs:line 32
   at System.CommandLine.Handler.<>c__DisplayClass2_0`1.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   
   ```

File : [WRobot.zip](https://github.com/puff/EazyDevirt/files/13376259/WRobot.zip)

Vendor : https://wrobot.eu/

**Comment by puff** [comment]
Read notes https://github.com/puff/EazyDevirt#notes
and using `--verbose 3` option helps with debugging it
